services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: siam_api
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/siam
      - RUTA_ARCHIVOS_BIBLIOTECA=./archivos_biblioteca
      - NODE_ENV=development
    depends_on:
      - mongo
    volumes:
      - ./archivos_biblioteca:/app/archivos_biblioteca

  mongo:
    image: mongo:6
    container_name: siam_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
        - ./backend:/app 

volumes:
  mongo_data:
